---
## Result-App Deployment ##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: 9354165450/example:resultapp
        ports:
        - containerPort: 80
          name: result
---
## Result-App Service ##
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 30009
    name: result-service
  selector:
    app: result